name: Build and Test App Locally

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2

      - name: Download dependencies
        run: go mod download

      - name: Build app
        run: go build -o url-shortener ./cmd/url-shortener

      - name: Run tests
        run: go test ./...0